apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paas-backend
  template:
    metadata:
      labels:
        app: paas-backend
    spec:
      serviceAccountName: paas-backend-sa
      imagePullSecrets:
        - name: stackit-regcred
      containers:
        - name: paas-backend
          image: registry.onstackit.cloud/ryan-paas/paas-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: APP_ENV
              value: "production"
          envFrom:
            - secretRef:
                name: mongo-credentials
            - secretRef:
                name: backend-auth