apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paas-frontend-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ryanpaas.stackit.gg
      secretName: paas-frontend-tls
  rules:
    - host: ryanpaas.stackit.gg
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: paas-backend
                port:
                  number: 80
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: paas-frontend
                port:
                  number: 80
